config/routes.rb
Rails.application.routes.draw do
  resources :comentarios
  resources :tarefas
  devise_for :users
  get 'home/view'
  root 'home#view'

  resources :tarefa, only: [:show] do
    resources :comentarios, only: [:show, :index]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comentario.rb
class Comentario < ApplicationRecord
  has_one :tarefa
end

app/models/tarefa.rb
class Tarefa < ApplicationRecord
    has_many :comentario
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!

end

app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
  before_action :set_comentario, only: [:show, :edit, :update, :destroy]

  # GET /comentarios
  # GET /comentarios.json
  def index
    @comentarios = Comentario.all
  end

  # GET /comentarios/1
  # GET /comentarios/1.json
  def show
    @comentarios = Comentario.all
    options_for_select
  end

  # GET /comentarios/new
  def new
    @comentario = Comentario.new
    options_for_select
  end

  # GET /comentarios/1/edit
  def edit
    options_for_select
  end

  # POST /comentarios
  # POST /comentarios.json
  def create
    @comentario = Comentario.new(comentario_params)
   if(@comentario.usuario == '')
    @comentario.usuario = current_user.email
   end
    respond_to do |format|
      if @comentario.save
        format.html { redirect_to @comentario, notice: 'Comentario was successfully created.' }
        format.json { render :show, status: :created, location: @comentario }
      else
        format.html { render :new }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comentarios/1
  # PATCH/PUT /comentarios/1.json
  def update
    respond_to do |format|
      if @comentario.update(comentario_params)
        format.html { redirect_to @comentario, notice: 'Comentario was successfully updated.' }
        format.json { render :show, status: :ok, location: @comentario }
      else
        format.html { render :edit }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comentarios/1
  # DELETE /comentarios/1.json
  def destroy
    @comentario.destroy
    respond_to do |format|
      format.html { redirect_to comentarios_url, notice: 'Comentario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def tarefas_index
    @comentarios = Comentario.find(params[:id])
    @tarefas = @comentarios.tarefas
    render template: 'tarefas/index'
  end
  private
  def options_for_select
    @tarefas_options_for_select = Tarefa.all
    @Comentario_options_for_select = Comentario.all
  end
    # Use callbacks to share common setup or constraints between actions.
    def set_comentario
      @comentario = Comentario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comentario_params
      params.require(:comentario).permit(:tarefa_id, :id, :titulo, :conteudo, :usuario)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def view
  end
end

app/controllers/tarefas_controller.rb
class TarefasController < ApplicationController
  before_action :set_tarefa, only: [:show, :edit, :update, :destroy]
  
  # GET /tarefas
  # GET /tarefas.json
  def index
    @tarefas = Tarefa.all
    @comentarios_options_for_select = Comentario.all
    if params[:comentarios_id]
      @tarefas = Comentario.find(params[:comentarios_id]).includes(:comentarios).tarefas
  else
      @tarefa = Tarefa.all
  end
  end

  # GET /tarefas/1
  # GET /tarefas/1.json
  def show
  end

  # GET /tarefas/new
  def new
    @tarefa = Tarefa.new
  end

  # GET /tarefas/1/edit
  def edit
  end

  # POST /tarefas
  # POST /tarefas.json
  def create
    @tarefa = Tarefa.new(tarefa_params)

    respond_to do |format|
      if @tarefa.save
        format.html { redirect_to @tarefa, notice: 'Tarefa was successfully created.' }
        format.json { render :show, status: :created, location: @tarefa }
      else
        format.html { render :new }
        format.json { render json: @tarefa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tarefas/1
  # PATCH/PUT /tarefas/1.json
  def update
    respond_to do |format|
      if @tarefa.update(tarefa_params)
        format.html { redirect_to @tarefa, notice: 'Tarefa was successfully updated.' }
        format.json { render :show, status: :ok, location: @tarefa }
      else
        format.html { render :edit }
        format.json { render json: @tarefa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tarefas/1
  # DELETE /tarefas/1.json
  def destroy
    @tarefa.destroy
    respond_to do |format|
      format.html { redirect_to tarefas_url, notice: 'Tarefa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tarefa
      @tarefa = Tarefa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tarefa_params
      params.require(:tarefa).permit(:titulo, :conteudo, :usuario, :situação)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tarefas_helper.rb
module TarefasHelper
end

app/views/comentarios/_form.html.erb
<%= form_with(model: comentario, local: true) do |form| %>
  <% if comentario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comentario.errors.count, "error") %> prohibited this comentario from being saved:</h2>

      <ul>
        <% comentario.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :tarefa_id %>
    <%= form.collection_select(:tarefa_id,
       @tarefas_options_for_select, :id, :titulo)%>
  </div>

  <div class="field">
    <%= form.label :conteudo %>
    <%= form.text_area :conteudo %>
  </div>

  <div class="field" >
    <%= form.label :usuario%>
    <%= form.text_field :usuario, value: @comentario.usuario %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comentarios/edit.html.erb
<h1>Editing Comentario</h1>

<%= render 'form', comentario: @comentario %>

<%= link_to 'Show', @comentario %> |
<%= link_to 'Back', comentarios_path %>

app/views/comentarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comentarios</h1>

<table>
  <thead>
    <tr>
      <th>Tarefa</th>
      <th>Conteudo</th>
      <th>Usuario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comentarios.each do |comentario| %>
      <tr>
        <td><%= comentario.tarefa_id %></td>
        <td><%= comentario.conteudo %></td>
        <td><%= comentario.usuario %></td>
        <td><%= link_to 'Show', comentario %></td>
        <td><%= link_to 'Edit', edit_comentario_path(comentario) %></td>
        <td><%= link_to 'Destroy', comentario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Voltar para tarefas', tarefas_path %> 
<%= link_to 'New Comentario', new_comentario_path %>

app/views/comentarios/new.html.erb
<h1>New Comentario</h1>

<%= render 'form', comentario: @comentario %>

<%= link_to 'Back', comentarios_path %>

app/views/comentarios/show.html.erb
<h1><%= "comentatios para a tarefa: #{@comentario.tarefa_id}"%> </h1>
<tbody>
  <% @comentarios.each do |comentario| %>
  <% if @comentario.tarefa_id == comentario.tarefa_id %>
  <tr>
      <p>
        <strong>Comentario::</strong>
        <%= comentario.conteudo %>
      </p>
      <p>
        <strong>Usuario:</strong>
        <%= comentario.usuario %>
      </p>
      <%= link_to 'Editar comentario', edit_comentario_path(comentario) %> |
    </tr>
  <% end %>
  
  <% end %>
</tbody>
<br><br><br><br>
<%= link_to 'Back', comentarios_path %>

app/views/home/view.html.erb
<head>
    <h1> CRUD para Tarefas</h1>
</head>
<body>
        <%= button_to "Cadastrar Tarefa", tarefas_path, :id => "open-contacts-dialog-btn",
        :class => "inbox-sf-add-btn tip", :method => :get %>
             <br>
        <%= button_to "Cadastrar comentarios", comentarios_path, :id => "open-contacts-dialog-btn",
        :class => "inbox-sf-add-btn tip", :method => :get %>
        <br>
        <br>

  
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Devise</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  
<p class="navbar-text float-right">
    <% if user_signed_in? %>
      Logado como: <strong><%= current_user.email %></strong>.
      <%= link_to 'Editar perfil', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
      <%= link_to "Registrar-se", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
  </head>

  <body>
    
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/tarefas/_form.html.erb
<%= form_with(model: tarefa, local: true) do |form| %>
  <% if tarefa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tarefa.errors.count, "error") %> prohibited this tarefa from being saved:</h2>

      <ul>
        <% tarefa.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :titulo %>
    <%= form.text_field :titulo %>
  </div>

  <div class="field">
    <%= form.label :conteudo %>
    <%= form.text_area :conteudo %>
  </div>

  <div class="field">
    <%= form.label :usuario %>
    <%= form.text_field :usuario %>
  </div>

  <div class="field">
    <%= form.label :situação %>
    <%= form.text_area :situação %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tarefas/edit.html.erb
<h1>Editing Tarefa</h1>

<%= render 'form', tarefa: @tarefa %>

<%= link_to 'Show', @tarefa %> |
<%= link_to 'Back', tarefas_path %>

app/views/tarefas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tarefas</h1>

<table>
  <thead>
    <tr>
      <th>Titulos</th>
      <th>Conteudo</th>
      <th>Usuario</th>
      <th>situação</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tarefas.each do |tarefa| %>
    <tr>
      <td><%= tarefa.titulo %></td>
      <td><%= tarefa.conteudo %></td>
      <td><%= tarefa.usuario %></td>
      <td><%= tarefa.situação %></td>
      <td><%= link_to 'Mostrar detalhes', tarefa %></td>
      <td><%= link_to 'Edit', edit_tarefa_path(tarefa) %></td>
      <td><%= link_to 'Destroy', tarefa, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <td>comentarios:</td>
      <td>
        <% @comentarios_options_for_select.each do |coment|%>
        <%if coment.tarefa_id == tarefa.id%>
        <%= '|'%>   
        <%= link_to coment.conteudo, tarefa_comentario_path(tarefa.id, coment.id)%>
        <%= '|'%>
        <% end %>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'ir para Comentarios', comentarios_path %>
<%= link_to 'New Tarefa', new_tarefa_path %>

app/views/tarefas/new.html.erb
<h1>New Tarefa</h1>

<%= render 'form', tarefa: @tarefa %>

<%= link_to 'Back', tarefas_path %>

app/views/tarefas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @tarefa.titulo %>
</p>

<p>
  <strong>Conteudo:</strong>
  <%= @tarefa.conteudo %>
</p>

<p>
  <strong>Usuario:</strong>
  <%= @tarefa.usuario %>
</p>

<p>
  <strong>Situação:</strong>
  <%= @tarefa.situação %>
</p>

<%= link_to 'Edit', edit_tarefa_path(@tarefa) %> |
<%= link_to 'Back', tarefas_path %>